### ISSUE TITLE
'rsh_estimate' returns '0's for coefficient values

### ISSUE THREAD

**Issue by lisalan520** [synthicity/sanfran_urbansim#12]
Hi,

I got '0's for all coefficients when I ran sim.run(["rsh_estimate"]) in Estimation.ipynb. And it re-wrote my rsh.yaml file. The Hedonic Example notebook returned 'correct'-looking values with directly running the fit function. Below are two captures. Have you got any similar issues? Thanks!

Estimation.ipynb capture 
![image](https://cloud.githubusercontent.com/assets/10837773/6578677/e856264a-c71b-11e4-8201-83116b395717.png)

Hedonic Example.ipynb capture
![image](https://cloud.githubusercontent.com/assets/10837773/6578843/da7d02f4-c71c-11e4-89d4-6820adb55f60.png)

**Comment by fscottfoti** [comment]
Not entirely sure - there might be a filter that is removing most/all of the records?

**Comment by lisalan520** [comment]
It is a little odd.. as I didn't change any thing. The fit filters in the rsh.yaml are:

fit_filters:
- unit_lot_size > 0
- year_built > 1000
- year_built < 2020
- unit_sqft > 100
- unit_sqft < 20000

which is the same as is in Hedonic Example...

**Comment by lisalan520** [comment]
Hi @fscottfoti, 
Just solved the problem by removing line 20-23 in dataset.py. They are the 'filters' you mentioned. Thanks!

**Comment by fscottfoti** [comment]
Great!  I suspect there was no variability in one or more columns when the filters removed enough data.  We should probably be detecting that error directly.
