### ISSUE TITLE
'module' object has no attribute 'table_source'

### ISSUE THREAD

**Issue by fivejjs** [synthicity/sanfran_urbansim#13]
in notebook Hedonic Example
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f3c40d287649> in <module>()
----> 1 @sim.table_source('buildings')
      2 def buildings(store):
      3     df = store['buildings']
      4     return df
      5 

AttributeError: 'module' object has no attribute 'table_source'

**Comment by jiffyclub** [comment]
Thanks, must not have missed that notebook when I was updating `table_source` instances.

**Comment by jiffyclub** [comment]
This will be be fixed by #14.
